sudo: false
language: ruby
rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - ruby-head
  - jruby-9.2.0.0
  - jruby-head

before_install: gem install bundler -v 1.16.2
script: bundle exec rspec
cache: bundler
